modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ModdingForBlockheads/Balm/issues"
[[mods]]
modId="balmforge"
version="${file.jarVersion}"
displayName="Balm"
displayURL="https://blay09.net/"
logoFile="balm-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Abstraction Layer (but not really)™ for Blay's multiplatform mods
'''
[[dependencies.balmforge]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.balmforge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
