modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/Balm/issues"
[[mods]]
modId="balm"
version="${file.jarVersion}"
displayName="Balm"
displayURL="https://blay09.net/"
logoFile="balm-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Abstraction Layer (but not really)™ for Blay's multiplatform mods
'''
[[dependencies.balm]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.balm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
